//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LGallegosEmisonEntities : DbContext
    {
        public LGallegosEmisonEntities()
            : base("name=LGallegosEmisonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emisor> Emisors { get; set; }
    
        public virtual int AddEmisor(string rFC, Nullable<System.DateTime> fechaInicioOperacion, Nullable<decimal> capital)
        {
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            var fechaInicioOperacionParameter = fechaInicioOperacion.HasValue ?
                new ObjectParameter("FechaInicioOperacion", fechaInicioOperacion) :
                new ObjectParameter("FechaInicioOperacion", typeof(System.DateTime));
    
            var capitalParameter = capital.HasValue ?
                new ObjectParameter("Capital", capital) :
                new ObjectParameter("Capital", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddEmisor", rFCParameter, fechaInicioOperacionParameter, capitalParameter);
        }
    
        public virtual int DeleteEmisor(Nullable<int> idEmisor)
        {
            var idEmisorParameter = idEmisor.HasValue ?
                new ObjectParameter("IdEmisor", idEmisor) :
                new ObjectParameter("IdEmisor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteEmisor", idEmisorParameter);
        }
    
        public virtual ObjectResult<GetAllEmisor_Result> GetAllEmisor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllEmisor_Result>("GetAllEmisor");
        }
    
        public virtual ObjectResult<GetByIdEmisor_Result> GetByIdEmisor(Nullable<int> idEmisor)
        {
            var idEmisorParameter = idEmisor.HasValue ?
                new ObjectParameter("IdEmisor", idEmisor) :
                new ObjectParameter("IdEmisor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetByIdEmisor_Result>("GetByIdEmisor", idEmisorParameter);
        }
    
        public virtual int UpdateEmisor(Nullable<int> idEmisor, string rFC, Nullable<System.DateTime> fechaInicioOperacion, Nullable<decimal> capital)
        {
            var idEmisorParameter = idEmisor.HasValue ?
                new ObjectParameter("IdEmisor", idEmisor) :
                new ObjectParameter("IdEmisor", typeof(int));
    
            var rFCParameter = rFC != null ?
                new ObjectParameter("RFC", rFC) :
                new ObjectParameter("RFC", typeof(string));
    
            var fechaInicioOperacionParameter = fechaInicioOperacion.HasValue ?
                new ObjectParameter("FechaInicioOperacion", fechaInicioOperacion) :
                new ObjectParameter("FechaInicioOperacion", typeof(System.DateTime));
    
            var capitalParameter = capital.HasValue ?
                new ObjectParameter("Capital", capital) :
                new ObjectParameter("Capital", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateEmisor", idEmisorParameter, rFCParameter, fechaInicioOperacionParameter, capitalParameter);
        }
    }
}
